CREATE TABLE IF NOT EXISTS agents (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    region VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL,
    last_update DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
